;             
CREATE USER IF NOT EXISTS DIGITALVALVE SALT '0dd1f31330560c58' HASH 'add81057b8c211fa3cc298d9fa717d9697d73935af2ee3a0bd22b92d20ad7d93' ADMIN; 
CREATE CACHED TABLE PUBLIC.ANALYTIC(
    ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    LAST_EXECUTED_ON LONG,
    ORDINAL_POSITION INTEGER
);              
ALTER TABLE PUBLIC.ANALYTIC ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);               
-- 11 +/- SELECT COUNT(*) FROM PUBLIC.ANALYTIC;               
CREATE CACHED TABLE PUBLIC.ANALYTIC_DATA(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_ID VARCHAR(50),
    NAME VARCHAR(50),
    ACTION_LIMIT DOUBLE,
    ALARM_LIMIT DOUBLE,
    BASELINE DOUBLE,
    MEASUREMENT_UNIT VARCHAR(50),
    MEASUREMENT_UNIT_BASELINE CHAR(10),
    AGGREGATION_TYPE VARCHAR(50),
    VALUE DOUBLE,
    PROJECTED_FAILURE_DATE LONG,
    ALERT_NAME VARCHAR(100),
    ALERT_DESCRIPTION VARCHAR(255),
    ORDINAL_POSITION INTEGER
);
ALTER TABLE PUBLIC.ANALYTIC_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);          
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.ANALYTIC_DATA;           
CREATE CACHED TABLE PUBLIC.ALERT_RECOMMENDATION(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_DATA_ID VARCHAR(50),
    RECOMMENDATION VARCHAR(255),
    ORDINAL_POSITION INTEGER
);         
ALTER TABLE PUBLIC.ALERT_RECOMMENDATION ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID);   
-- 14 +/- SELECT COUNT(*) FROM PUBLIC.ALERT_RECOMMENDATION;   
CREATE CACHED TABLE PUBLIC.DATA_FILTER_CRITERIA(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_ID VARCHAR(50),
    NAME VARCHAR(50),
    DATA_TYPE VARCHAR(50),
    VALUE VARCHAR(50),
    MEASUREMENT_UNIT VARCHAR(50),
    ORDINAL_POSITION INTEGER
);  
ALTER TABLE PUBLIC.DATA_FILTER_CRITERIA ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.DATA_FILTER_CRITERIA;    
CREATE CACHED TABLE PUBLIC.OXIDATION_BIN(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_ID VARCHAR(50),
    TEMP_BIN_1 LONG,
    TEMP_BIN_2 LONG,
    TEMP_BIN_3 LONG,
    TEMP_BIN_4 LONG,
    TEMP_BIN_5 LONG,
    TEMP_BIN_6 LONG
);  
ALTER TABLE PUBLIC.OXIDATION_BIN ADD CONSTRAINT PUBLIC.CONSTRAINT_F4 PRIMARY KEY(ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OXIDATION_BIN;           
CREATE CACHED TABLE PUBLIC.CREEP_BIN(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_ID VARCHAR(50),
    DATE LONG,
    PRESS_BIN_1 DOUBLE,
    PRESS_BIN_2 DOUBLE,
    PRESS_BIN_3 DOUBLE,
    PRESS_BIN_4 DOUBLE,
    PRESS_BIN_5 DOUBLE,
    PRESS_BIN_6 DOUBLE,
    TEMP_BIN_1 LONG,
    TEMP_BIN_2 LONG,
    RPM_BIN_1 LONG,
    RPM_BIN_2 LONG
);              
ALTER TABLE PUBLIC.CREEP_BIN ADD CONSTRAINT PUBLIC.CONSTRAINT_D PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CREEP_BIN;               
CREATE CACHED TABLE PUBLIC.HST_DATA(
    ID VARCHAR(50) NOT NULL,
    AGGREGATION_TYPE VARCHAR(50),
    COEFF_M DOUBLE,
    COEFF_B DOUBLE,
    FROM_DATE LONG,
    TO_DATE LONG
);    
ALTER TABLE PUBLIC.HST_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_F2 PRIMARY KEY(ID);              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HST_DATA;
CREATE CACHED TABLE PUBLIC.HST_DATA_RAW(
    DATA_ID VARCHAR(50) NOT NULL,
    TIME_STAMP LONG NOT NULL,
    VALUE VARCHAR(50)
);         
ALTER TABLE PUBLIC.HST_DATA_RAW ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(DATA_ID, TIME_STAMP);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HST_DATA_RAW;            
CREATE CACHED TABLE PUBLIC.HST_DATA_COMPRESSION_1(
    DATA_ID VARCHAR(50) NOT NULL,
    TIME_STAMP LONG NOT NULL,
    VALUE VARCHAR(50)
);               
ALTER TABLE PUBLIC.HST_DATA_COMPRESSION_1 ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(DATA_ID, TIME_STAMP);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HST_DATA_COMPRESSION_1;  
CREATE CACHED TABLE PUBLIC.HST_DATA_COMPRESSION_2(
    DATA_ID VARCHAR(50) NOT NULL,
    TIME_STAMP LONG NOT NULL,
    VALUE VARCHAR(50)
);               
ALTER TABLE PUBLIC.HST_DATA_COMPRESSION_2 ADD CONSTRAINT PUBLIC.CONSTRAINT_B8 PRIMARY KEY(DATA_ID, TIME_STAMP);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HST_DATA_COMPRESSION_2;  
CREATE CACHED TABLE PUBLIC.OTHER_SETTING(
    ID VARCHAR(50) NOT NULL,
    ANALYTIC_ID VARCHAR(50),
    NAME VARCHAR(50),
    DATA_TYPE VARCHAR(50),
    VALUE VARCHAR(50),
    MEASUREMENT_UNIT VARCHAR(50),
    ORDINAL_POSITION INTEGER
);         
ALTER TABLE PUBLIC.OTHER_SETTING ADD CONSTRAINT PUBLIC.CONSTRAINT_8 PRIMARY KEY(ID);          
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.OTHER_SETTING;           
ALTER TABLE PUBLIC.ANALYTIC_DATA ADD CONSTRAINT PUBLIC.CONSTRAINT_6A FOREIGN KEY(ANALYTIC_ID) REFERENCES PUBLIC.ANALYTIC(ID) NOCHECK;         
ALTER TABLE PUBLIC.HST_DATA_COMPRESSION_1 ADD CONSTRAINT PUBLIC.CONSTRAINT_B83 FOREIGN KEY(DATA_ID) REFERENCES PUBLIC.HST_DATA(ID) NOCHECK;   
ALTER TABLE PUBLIC.CREEP_BIN ADD CONSTRAINT PUBLIC.CONSTRAINT_D0 FOREIGN KEY(ANALYTIC_ID) REFERENCES PUBLIC.ANALYTIC(ID) NOCHECK;             
ALTER TABLE PUBLIC.HST_DATA_RAW ADD CONSTRAINT PUBLIC.CONSTRAINT_36 FOREIGN KEY(DATA_ID) REFERENCES PUBLIC.HST_DATA(ID) NOCHECK;              
ALTER TABLE PUBLIC.OTHER_SETTING ADD CONSTRAINT PUBLIC.CONSTRAINT_84 FOREIGN KEY(ANALYTIC_ID) REFERENCES PUBLIC.ANALYTIC(ID) NOCHECK;         
ALTER TABLE PUBLIC.HST_DATA_COMPRESSION_2 ADD CONSTRAINT PUBLIC.CONSTRAINT_B832 FOREIGN KEY(DATA_ID) REFERENCES PUBLIC.HST_DATA(ID) NOCHECK;  
ALTER TABLE PUBLIC.OXIDATION_BIN ADD CONSTRAINT PUBLIC.CONSTRAINT_F46 FOREIGN KEY(ANALYTIC_ID) REFERENCES PUBLIC.ANALYTIC(ID) NOCHECK;        
ALTER TABLE PUBLIC.ALERT_RECOMMENDATION ADD CONSTRAINT PUBLIC.CONSTRAINT_4D FOREIGN KEY(ANALYTIC_DATA_ID) REFERENCES PUBLIC.ANALYTIC_DATA(ID) NOCHECK;        
ALTER TABLE PUBLIC.DATA_FILTER_CRITERIA ADD CONSTRAINT PUBLIC.CONSTRAINT_C8 FOREIGN KEY(ANALYTIC_ID) REFERENCES PUBLIC.ANALYTIC(ID) NOCHECK;  
